# Generated by Django 4.2.7 on 2023-11-22 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
