# Generated by Django 4.2.7 on 2023-11-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
